---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-clickhouse-com4
  namespace: clickhouse
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: clickhouse
  local:
    path: /mnt/data/clickhouse
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - com4
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv-clickhouse-com5
#spec:
#  capacity:
#    storage: 80Gi
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: clickhouse
#  local:
#    path: /mnt/data/clickhouse
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - com5
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc-0
  namespace: clickhouse
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
  storageClassName: clickhouse
  volumeName: pv-clickhouse-com4
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: clickhouse-pvc-1
#  namespace: clickhouse
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 80Gi
#  storageClassName: clickhouse
#
