---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-nfs-com3
  namespace: clickhouse
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data/zookeeper
    server: com3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-nfs-com4
  namespace: clickhouse
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data/zookeeper
    server: com4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-nfs-com5
  namespace: clickhouse
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data/zookeeper
    server: com5
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc-0
  namespace: clickhouse
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-zookeeper-nfs-com3
  storageClassName: zookeeper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc-1
  namespace: clickhouse
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-zookeeper-nfs-com4
  storageClassName: zookeeper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc-2
  namespace: clickhouse
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-zookeeper-nfs-com5
  storageClassName: zookeeper
