from views.home import display_home_page
from views.job_informations import display_job_informations
from views.login import display_login_page
from views.user_information import display_user_information
from views.error import display_error_page
from views.filter_log import display_filter_log