from pages.home import display_home_page
from pages.job_informations import display_job_informations
from pages.api import get_dataframe
from pages.login import display_login_page
from pages.user_informations import display_user_information